# Generated by Django 5.2.1 on 2025-06-19 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
